### PR TITLE
Feature/FED Upgrade

### PR DESCRIPTION
**Pull request by dgkohn**
# Project Upgrade (FED)
- FED dependencies upgrades (package.json/yarn.lock)

### CODE REVIEW

**Comment by dgkohn** [comment]
@Holloway I haven't found any packages that had security issues for us to change in `package.json`. Any other suggestions on what to upgrade here? I could force minor bumps for each `devDependencies` and `dependencies`.

**Comment by holloway** [comment]
Hmm... I don't see much point in upgrading to Bootstrap v4.6.0 yet (it doesn't seem to fix any bugs that might affect us, and it might introduce other bugs).

Nor would upgrading to jQuery 3.6.0 give us anything.

I think it's probably best to just leave it with your suggested minor upgrades @dgkohn :smile:

**Review by holloway — APPROVED** [review]

**Comment by dgkohn** [comment]
```
 Major Update (Potentially breaking API changes):
 ◯ autoprefixer                             9.8.6   ❯  10.2.5  https://github.com/postcss/autoprefixer#readme
 ◯ ionicons                                 2.0.1   ❯  5.5.1   http://ionicons.com/
 ◯ node-sass                                4.14.1  ❯  5.0.0   https://github.com/sass/node-sass
 ◯ puppeteer                                5.5.0   ❯  8.0.0   https://github.com/puppeteer/puppeteer#readme
 ◯ @typescript-eslint/eslint-plugin devDep  3.10.1  ❯  4.19.0  https://github.com/typescript-eslint/typescript-eslint#readme
 ◯ @typescript-eslint/parser devDep         3.10.1  ❯  4.19.0  https://github.com/typescript-eslint/typescript-eslint#readme
 ◯ css-loader devDep                        3.6.0   ❯  5.2.0   https://github.com/webpack-contrib/css-loader
 ◯ html-webpack-plugin devDep               4.5.2   ❯  5.3.1   https://github.com/jantimon/html-webpack-plugin
 ◯ mini-css-extract-plugin devDep           0.9.0   ❯  1.3.9   https://github.com/webpack-contrib/mini-css-extract-plugin
 ◯ postcss-loader devDep                    3.0.0   ❯  5.2.0   https://github.com/webpack-contrib/postcss-loader
 ◯ sass-loader devDep                       9.0.3   ❯  11.0.1  https://github.com/webpack-contrib/sass-loader
 ◯ style-loader devDep                      1.3.0   ❯  2.0.0   https://github.com/webpack-contrib/style-loader
 ◯ svgo devDep                              1.3.2   ❯  2.2.2   https://github.com/svg/svgo
 ◯ svgo-loader devDep                       2.2.2   ❯  3.0.0   https://github.com/pozadi/svgo-loader
 ◯ webpack devDep                           4.46.0  ❯  5.28.0  https://github.com/webpack/webpack
 ◯ webpack-cli devDep                       3.3.12  ❯  4.5.0   https://github.com/webpack/webpack-cli#readme
```

**Comment by dgkohn** [comment]
> Hmm... I don't see much point in upgrading to Bootstrap v4.6.0 yet (it doesn't seem to fix any bugs that might affect us, and it might introduce other bugs).
> 
> Nor would upgrading to jQuery 3.6.0 give us anything.
> 
> I think it's probably best to just leave it with your suggested minor upgrades @dgkohn 😄

Thanks @holloway , will leave the comms in this PR for future reference.

**Pull request merged**
