### PR TITLE
Social Media FED

### PR DESCRIPTION
**Pull request by CliffRobinson**
[IAB-40](https://springload-nz.atlassian.net/browse/IAB-40)

@sarahframe had done the most important part of the FED, but I thought it best to make the link display conditional on that data being input. 

It also looks like there was some redundant backend settings that would only be confusing to leave in, so I pulled that out. If I've done the BED wrong plz let me know 👍 .

[IAB-40]: https://springload-nz.atlassian.net/browse/IAB-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sarahframe** [comment]
> [IAB-40](https://springload-nz.atlassian.net/browse/IAB-40)
> 
> @sarahframe had done the most important part of the FED, but I thought it best to make the link display conditional on that data being input.
> 
> It also looks like there was some redundant backend settings that would only be confusing to leave in, so I pulled that out. If I've done the BED wrong plz let me know 👍 .

Hi @CliffRobinson we need to keep those settings in the back end as they are. They are used in the IETF site

I agree with your if blocks in the template.

[IAB-40]: https://springload-nz.atlassian.net/browse/IAB-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by sarahframe — CHANGES_REQUESTED** [review]
Please leave models.py as it is and delete the migration file

**Comment by CliffRobinson** [comment]
> Please leave models.py as it is and delete the migration file

OK, that's done, but perhaps there should be some labels in the CMS that make it clear which social media setting corresponds to which site? If I assumed that the IETF site settings apply to the IAB site there's a reasonable chance the user will too.

**Comment by sarahframe** [comment]
> > Please leave models.py as it is and delete the migration file
> 
> OK, that's done, but perhaps there should be some labels in the CMS that make it clear which social media setting corresponds to which site? If I assumed that the IETF site settings apply to the IAB site there's a reasonable chance the user will too.

I had thought about that and discussed with Andrew. He suggested we leave it as it is in case IETF want to add the same social links to their site in the future. @AndrewCalderSpringload do you still think it's best to leave as is or do you think some clear labels would make more sense

**Review by sarahframe — APPROVED** [review]

**Pull request merged**
